version: '3.5'
services:

  mysql-server:
    image: mysql:5.7
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db/mysql_data:/var/lib/mysql
    user: "1000:50" # remove at Photon
    restart: always

  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:${VERSION}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: always

  zabbix-server-mysql:
    image: zabbix/zabbix-server-mysql:${VERSION}
    depends_on:
      - mysql-server
      - zabbix-java-gateway
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 10051:10051
    restart: always

  zabbix-web-nginx-mysql:
    build: ./nginx/
    depends_on:
      - mysql-server
      - zabbix-server-mysql
      - zabbix-java-gateway
    environment:
      - DB_SERVER_HOST=mysql-server
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - ZBX_SERVER_HOST=zabbix-server
      - PHP_TZ="Asia/Tokyo"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - zabbix-server-mysql:zabbix-server
    ports:
      - 80:80
    restart: always

  zabbix-agent:
    image: zabbix/zabbix-agent:${VERSION}
    links:
      - zabbix-server-mysql:zabbix-server
    volumes:
      - /etc/localtime:/etc/localtime:ro
    # networks:
    #   zbx_net_backend:
    #   zbx_net_frontend:
    restart: always

