version: '2'
services:

  mysql-server:
    image: mysql:5.7
    user: "1000:50"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=hoge
      - MYSQL_PASSWORD=hoge
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    restart: always
